os:
  - linux
  - osx

language: c

compiler: gcc

sudo: false

addons:
  apt:
    packages:
      - make
      - gcc-multilib
      - libpcap0.8
      - libpcap0.8-dev

cache:
  directories:
  - $HOME/.ccache

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

before_script:
  - make clean
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '/linux/I s/^/#/' Makefile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '/-DOPENBSD/ s/^#//' Makefile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '1,/LDLIB/s/^#LDLIB/LDLIB/' Makefile ; fi

script:
    make
