os:
  - linux
  - osx

language: c

compiler: gcc

sudo: false

addons:
  apt:
    packages:
      - make
      - gcc-multilib
      - libpcap0.8
      - libpcap0.8-dev

cache:
  directories:
  - $HOME/.ccache

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

before_script:
    make clean

script:
    make
